#lang racket/base

(require marv/drivers/gcp/crud)

(provide compute-type-map)

; Returns id of resource operation e.g. compute.instance.get
(define (compute-type-map type op) (type-to-crud-op type-map type op))

; TODO - find way to auto-generate this (heuristics?)
(define type-map
  (make-immutable-hasheq
   `(
     (perInstanceConfig . ,(crud 'compute.instanceGroupManagers.patchPerInstanceConfigs
                                 'compute.instanceGroupManagers.listPerInstanceConfigs
                                 'compute.instanceGroupManagers.patchPerInstanceConfig
                                 'compute.instanceGroupManagers.deletePerInstanceConfigs))

     (acceleratorType . acceleratorTypes)
     (address . addresses)
     (autoscaler . autoscalers)
     (backendBucket . backendBuckets)
     (backendService . backendServices)
     (diskType . diskTypes)
     (disk . disks)
     (externalVpnGateway . externalVpnGateways)
     (firewallPolicy . firewallPolicies)
     (firewall . firewalls)
     (forwardingRule . forwardingRules)
     (globalAddress . globalAddresses)
     (globalForwardingRule . globalForwardingRules)
     (globalNetworkEndpointGroup . globalNetworkEndpointGroups)
     (globalOperation . globalOperations)
     (globalOrganizationOperation . globalOrganizationOperations)
     (globalPublicDelegatedPrefix . globalPublicDelegatedPrefixes)
     (healthCheck . healthChecks)
     (httpHealthCheck . httpHealthChecks)
     (httpsHealthCheck . httpsHealthChecks)
     (imageFamilyView . imageFamilyViews)
     (image . images)
     (instanceGroupManager . instanceGroupManagers)
     (instanceGroup . instanceGroups)
     (instanceTemplate . instanceTemplates)
     (instance . instances)
     (interconnectAttachment . interconnectAttachments)
     (interconnectLocation . interconnectLocations)
     (interconnect . interconnects)
     (licenseCode . licenseCodes)
     (license . licenses)
     (machineImage . machineImages)
     (machineType . machineTypes)
     (networkAttachment . networkAttachments)
     (networkEdgeSecurityService . networkEdgeSecurityServices)
     (networkEndpointGroup . networkEndpointGroups)
     (networkFirewallPolicy . networkFirewallPolicies)
     (network . networks)
     (nodeGroup . nodeGroups)
     (nodeTemplate . nodeTemplates)
     (nodeType . nodeTypes)
     (packetMirroring . packetMirrorings)
     (project . projects)
     (publicAdvertisedPrefixe . publicAdvertisedPrefixes)
     (publicDelegatedPrefixe . publicDelegatedPrefixes)
     (regionAutoscaler . regionAutoscalers)
     (regionBackendService . regionBackendServices)
     (regionCommitment . regionCommitments)
     (regionDiskType . regionDiskTypes)
     (regionDisk . regionDisks)
     (regionHealthCheckService . regionHealthCheckServices)
     (regionHealthCheck . regionHealthChecks)
     (regionInstanceGroupManager . regionInstanceGroupManagers)
     (regionInstanceGroup . regionInstanceGroups)
     (regionInstanceTemplate . regionInstanceTemplates)
     (regionInstance . regionInstances)
     (regionNetworkEndpointGroup . regionNetworkEndpointGroups)
     (regionNetworkFirewallPolicy . regionNetworkFirewallPolicies)
     (regionNotificationEndpoint . regionNotificationEndpoints)
     (regionOperation . regionOperations)
     (regionSecurityPolicy . regionSecurityPolicies)
     (regionSslCertificate . regionSslCertificates)
     (regionSslPolicy . regionSslPolicies)
     (regionTargetHttpProxy . regionTargetHttpProxies)
     (regionTargetHttpsProxy . regionTargetHttpsProxies)
     (regionTargetTcpProxy . regionTargetTcpProxies)
     (regionUrlMap . regionUrlMaps)
     (region . regions)
     (reservation . reservations)
     (resourcePolicy . resourcePolicies)
     (router . routers)
     (route . routes)
     (securityPolicy . securityPolicies)
     (serviceAttachment . serviceAttachments)
     (snapshot . snapshots)
     (sslCertificate . sslCertificates)
     (sslPolicy . sslPolicies)
     (subnetwork . subnetworks)
     (targetGrpcProxy . targetGrpcProxies)
     (targetHttpProxy . targetHttpProxies)
     (targetHttpsProxy . targetHttpsProxies)
     (targetInstance . targetInstances)
     (targetPool . targetPools)
     (targetSslProxy . targetSslProxies)
     (targetTcpProxy . targetTcpProxies)
     (targetVpnGateway . targetVpnGateways)
     (urlMap . urlMaps)
     (vpnGateway . vpnGateways)
     (vpnTunnel . vpnTunnels)
     (zoneOperation . zoneOperations)
     (zone . zones)

     )))